tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#46556b",
                "on-primary-fixed": "#2a1700",
                "primary-container": "#f59e0a",
                "surface-container-high": "#141f38",
                "on-primary-container": "#472a00",
                "secondary-container": "#005ac2",
                "surface-container-highest": "#192540",
                "surface-tint": "#ffad3a",
                "outline": "#6d758c",
                "on-secondary-fixed": "#003271",
                "surface-container": "#0f1930",
                "error-container": "#b92902",
                "error": "#ff7351",
                "inverse-primary": "#865400",
                "primary-fixed-dim": "#e79400",
                "surface-bright": "#1f2b49",
                "primary": "#ffad3a",
                "surface-variant": "#192540",
                "secondary-fixed": "#bfd1ff",
                "surface-dim": "#060e20",
                "surface-container-lowest": "#000000",
                "tertiary-dim": "#bacae4",
                "on-primary": "#543300",
                "tertiary": "#d7e6ff",
                "secondary": "#699cff",
                "on-tertiary-container": "#3c4c61",
                "on-surface-variant": "#a3aac4",
                "inverse-surface": "#faf8ff",
                "surface-container-low": "#091328",
                "on-surface": "#dee5ff",
                "secondary-dim": "#699cff",
                "secondary-fixed-dim": "#a9c4ff",
                "on-tertiary": "#45546a",
                "primary-dim": "#e79400",
                "tertiary-fixed": "#c8d8f3",
                "error-dim": "#d53d18",
                "on-secondary-container": "#f7f7ff",
                "on-error": "#450900",
                "on-error-container": "#ffd2c8",
                "primary-fixed": "#f8a010",
                "tertiary-fixed-dim": "#bacae4",
                "background": "#0d1a37ff",
                "on-background": "#dee5ff",
                "on-secondary-fixed-variant": "#004da8",
                "on-secondary": "#001e4a",
                "outline-variant": "#40485d",
                "inverse-on-surface": "#4d556b",
                "on-tertiary-fixed": "#29394e",
                "tertiary-container": "#c8d8f3",
                "surface": "#060e20",
                "on-primary-fixed-variant": "#563400"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
}